baseurl = "https://georgeheginbotham.netlify.app/"
title = "Portfolio & Services"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "George Heginbotham's work"
  copyright = "&copy;2020 George Heginbotham"
  sidebarAbout = [
    "I am a content creator and have a degree in Digital Marketing. I use my abilities to help brands grab attention and advertise.",
    "Currently based in Cape Town, South Africa"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "georgeshegin@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Restaurant Social Media Services"
  url = "RestaurantSocialMediaServices/"
  
    [[params.navlinks]]
  name = "Videography Services"
  url = "VideographyServices/"
  
    [[params.navlinks]]
  name = "Photography Services"
  url = "PhotographyServices/"
  
    [[params.navlinks]]
  name = "E-Book Creation Services"
  url = "E-BookCreationServices/"

  [[params.navlinks]]
  name = "Contact Me"
  url = "contact/"

  [params.social]
  email         = "georgeshegin@gmail.com"
  whatsapp      = "https://wa.me/qr/MZ6DTFWF2MUTC1"
  linkedin      = "https://www.linkedin.com/in/george-heginbotham-88a915127/"
  instagram     = "https://www.instagram.com/georgeheginbotham/"
  youtube       = "https://www.youtube.com/channel/UCoo48DdFqp-CcuVsYLFndKA"
  facebook      = "https://www.facebook.com/george.heginbotham"
